

- name: Prepare K3S agent
  template:
    src: k3s-agent.service.j2
    dest: /etc/systemd/system/k3s-agent.service

- name: Ensure k3s agent service
  service:
    name: k3s-agent
    state: started
    enabled: yes

