---
- name: Apt Update
  apt:
    update_cache: yes

- name: Ensure k3s prerequisites (Ubuntu)
  apt:
    name: '{{ debian_packages }}'
    state: present
    cache_valid_time: 3600

- name: "Ensure arptables-legacy once more"
  alternatives:
    name: "{{ item }}"
    path: "/usr/sbin/{{ item }}-legacy"
  loop:
    - "arptables"
    - "ebtables"
  ignore_errors: yes
